### ISSUE TITLE
Index out of range error (HIE vs HID issue)

### ISSUE THREAD

**Issue by ndonyapour** [bioexcel/biobb_structure_utils#14]
**Describe the bug**
Hello, I'm attempting to add partial charges and hydrogen to a protein structure using `str_check_add_hydrogens`, but I'm encountering the following error. It seems that the error is related to the HIE vs HID issue during the HIS conversion. 
```
Step 1: add_hydrogen --add_charges ADT --add_mode auto 
Running add_hydrogen. Options: --add_charges ADT --add_mode auto
Found 84 Residues requiring selection on adding H atoms
WARNING: fixing side chains, override with --no_fix_side
Running fixside. Options: --fix all
Found no residues with missing or unknown side chain atoms
Selection: auto
Replacing NHIS A1 by HIE
Replacing HIS A2 by HIE
Replacing HIS A8 by HIE
Replacing HIS A13 by HIE
Replacing HIS A15 by HIE
Replacing HIS A34 by HIE
Replacing HIS A62 by HIE
Replacing HIS A92 by HIE
Replacing HIS A94 by HIE
Replacing HIS A105 by HIE
Replacing HIS A117 by HIE
Replacing HIS A120 by HIE
Updating partial charges and atom types

2023-11-27 18:30:47,542 [MainThread  ] [INFO ]  Traceback (most recent call last):
  File "/usr/local/bin/check_structure", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/biobb_structure_checking/check_structure.py", line 52, in main
    StructureChecking(base_dir_path, vars(args)).launch()
  File "/usr/local/lib/python3.11/site-packages/biobb_structure_checking/structure_checking.py", line 93, in launch
    self.command_list(self.args['options'])
  File "/usr/local/lib/python3.11/site-packages/biobb_structure_checking/structure_checking.py", line 226, in command_list
    if self._run_method(command, opts):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/biobb_structure_checking/structure_checking.py", line 319, in _run_method
    error_status = f_fix(self, opts, data_to_fix)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/biobb_structure_checking/commands/add_hydrogen.py", line 163, in fix
    strcheck.strucm.add_hydrogens(
  File "/usr/local/lib/python3.11/site-packages/biobb_structure_checking/structure_manager.py", line 1437, in add_hydrogens
    self.update_atom_charges(add_charges)
  File "/usr/local/lib/python3.11/site-packages/biobb_structure_checking/structure_manager.py", line 338, in update_atom_charges
    atm.pqr_charge = self.res_library.get_atom_def(rcode, atm.id).chrg
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/biobb_structure_checking/libs/residue_lib_manager.py", line 77, in get_atom_def
    while resid_def.ats[i].id != at_id and i < len(resid_def.ats):
          ~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**To Reproduce**
I'm running `str_check_add_hydrogens` from `biobb_structure_utils:4.1.0--pyhdfd78af_0` docker container using the following arguments 
```
    str_check_add_hydrogens --config 
    '{"charges": true, "mode": "auto", "ph": 7.4, "list": "", "keep_canonical_resnames": false}' \
    --input_structure_path \
    /var/lib/cwl/stg98153775-225a-454b-822c-7e2b516bdf10/receptor_pdb4amber.pdb \
    --output_structure_path \
    pdb.pdbqt
```
I will attach receptor_pdb4amber.pdb here.
**Expected behavior**
It seems that the first HIS in the PDB file should be converted into HID instead of HIE.

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Python version: 3.11.5
 - BioBB version 4.1.0

**Additional context**
Here is the input file 
[input.zip](https://github.com/bioexcel/biobb_structure_utils/files/13490895/input.zip)

I appreciate your help!

**Comment by gbayarri** [comment]
Hi,

It seems that there is a leftover atom in the residue THR 123:

`ATOM    998  OXT THR A 123     -14.250  17.212  21.346  1.00  0.00           O`

Removing this atom it should work.

Best.

**Comment by ndonyapour** [comment]
Thank you for your response. The issue has been fixed by removing the OXT atom!

Best regards.
